### PR TITLE
fix(Demo): fixed table demo reorder

### LINKED ISSUE #2169: Demos: Table column reordering is not working
The table column order should update when the order is changed in the dropdown.

### PR DESCRIPTION
**Pull request by atlwendy**
closes #2169

### CODE REVIEW

File: projects/demo/src/app/components/table/table.component.ts [hunk 1]
```diff
@@ -282,6 +282,7 @@ export class TableComponent implements OnInit, AfterViewInit, OnDestroy {
     moveItemInArray(columns, event.previousIndex, event.currentIndex);
 
     this.allPossibleColumns = columns;
+    this.setVisibleColumns();
```
Comment (benjamincharity) [inline projects/demo/src/app/components/table/table.component.ts:285]: rofl I was hoping it was something simple 😂

**Review by benjamincharity — APPROVED** [review]
