### PR TITLE
feat(drawer): fixed header and footer

### LINKED ISSUE #1726: Drawer: Support fixed header and footer
The consumer should be able to pass header or footer content that remains fixed as the content scrolls.

---

### Requirements

- [ ] Create multiple transclusion slots
  - [ ] `ts-drawer-header`
  - [ ] Outputs into: `<ng-content select="ts-drawer-header"></ng-content>`
  - [ ] `ts-drawer-footer`
  - [ ] Outputs into: `<ng-content select="ts-drawer-footer"></ng-content>`
- [ ] Fixed header should have 1px gray bottom border
- [ ] Fixed footer should have 1px gray top border
- [ ] Center area should scroll on the y axis
  - [ ] All content should be visible (vs unable to reach under the fixed header/footer)
- [ ] Add tests
  - [ ] Verify content is passed through
- [ ] Add to usage docs
- [ ] Add to demo

#### Resources

- https://blog.angulartraining.com/tutorial-transclusion-content-projection-in-angular-1fea8f4421bd#dfb7

### PR DESCRIPTION
**Pull request by atlwendy**
closes #1726

### CODE REVIEW

File: terminus-ui/drawer/src/drawer-footer.component.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+  Component,
+  ViewEncapsulation,
+} from '@angular/core';
+
+/**
+ * The drawer footer UI Component
+ *
+ * @example
+ * <ts-drawer-footer
+ *             THIS IS MY FOOTER
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer-footer.component.ts]: This text content should be between `><`; currently it's added as a data attribute

File: terminus-ui/drawer/src/drawer-header.component.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+  Component,
+  ViewEncapsulation,
+} from '@angular/core';
+
+/**
+ * The drawer header UI Component
+ *
+ * @example
+ * <ts-drawer-header
+ *             THIS IS MY HEADER
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer-header.component.ts]: Same comment about location of text

File: demo/app/components/drawer/drawer.component.html [hunk 3]
```diff
@@ -23,6 +23,9 @@
       class="first-drawer"
       #drawer
     >
+      <ts-drawer-header>
+        <h4>HEADER</h4>
+      </ts-drawer-header>
       <div tsVerticalSpacing class="content">
```
Comment (benjamincharity) [inline demo/app/components/drawer/drawer.component.html]: Maybe we make this class more specific? It seems like we're picking up some padding styles meant for primary pages:

```
router-outlet + * .content {
    padding: 2rem;
}
```

File: demo/app/components/drawer/drawer.component.html [hunk 4]
```diff
@@ -41,6 +44,12 @@
           </ts-radio-group>
         </p>
       </div>
+      <div style="min-height: 600px; ">
```
Comment (benjamincharity) [inline demo/app/components/drawer/drawer.component.html]: It would be amazing to have 'real' content in here for a realistic demo. Maybe just some duplicated paragraphs with spacing?

eg

```html
  <p tsVerticalSpacing>
    Doloribus quis exercitationem sint sequi illo. Assumenda ducimus quae quam. Ipsum ut dolor.
  </p>
```

Bonus points if the viewer can check/uncheck a checkbox to show/hide the content so they can see with/without scrollable content. (not necessary though 😄)

File: demo/app/components/drawer/drawer.component.scss [hunk 5]
```diff
@@ -13,3 +13,22 @@
...
+.ts-drawer-footer {
+  padding-top: 15px;
+  background-color: #000;
+  color: white;
+  width: 100%;
+  height: 50px;
+}
+
+.content {
+  margin-top: 60px;
```
Comment (benjamincharity) [inline demo/app/components/drawer/drawer.component.scss]: Making the consumer responsible for the header/footer spacing is definitely viable. What do you think about handling this for the consumer? (asking because I have a feeling this will be our first request)

Possibly in the header/footer components, each has a getter that returns its size using our window service? Then the drawer component can grab those and set styles to create the header/footer space?

File: demo/app/components/drawer/drawer.component.html [hunk 6]
```diff
@@ -92,6 +101,18 @@
           The #1 software development tool used by agile teams.
           Visual regression testing is the ability to cross-reference snapshots of a product, highlighting pixel differences — returning fast feedback on the current state of the screen.
         </div>
+        <div>
+          <img src="https://d3vv6lp55qjaqc.cloudfront.net/items/20322G0V3H2j3n2M2o3l/nice%20laptop%3Ascreen%20elevation.png">
```
Comment (benjamincharity) [inline demo/app/components/drawer/drawer.component.html]: Thoughts on using something like https://placeholder.com/ instead? This way we aren't paying for the traffic and don't need to worry about these links going away..

File: terminus-ui/drawer/src/drawer.component.scss [hunk 7]
```diff
@@ -98,6 +99,26 @@ $ts-animation-duration: 400ms;
   &.ts-drawer--end {
     right: 0;
   }
+
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer.component.scss:110]: Not related to code in this PR but I must have missed in in the last one.. Background color of the drawer and both headers should be our pure white.

File: demo/app/components/drawer/drawer.component.scss [hunk 8]
```diff
@@ -13,3 +13,22 @@
     margin-right: 20px;
   }
 }
+
+.ts-drawer-header{
```
Comment (benjamincharity) [inline demo/app/components/drawer/drawer.component.scss]: IMO we should probably leave styling more default so that users can see what they get out of the box. Open to thoughts here though..

**Review by benjamincharity — CHANGES_REQUESTED** [review]
Couple notes.. nothing crazy. Excited to get this one out!

When you end up rebasing, the type is lowercase, but the scope should be capitalized. ie `feat(Drawer)` vs `feat(drawer)`

File: terminus-ui/drawer/src/drawer.component.scss (hunk 7 above)
Comment (benjamincharity) [reply terminus-ui/drawer/src/drawer.component.scss:110]: This was admittedly a lack of clarity in the issue on my part. Focused on functionality and kind of ignored style 🤦‍♂

File: terminus-ui/drawer/src/drawer-footer.component.ts [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+  ElementRef,
+  ViewEncapsulation,
+} from '@angular/core';
+
+/**
+ * The drawer footer UI Component
+ *
+ * @example
+ * <ts-drawer-footer>
+ *   THIS IS MY FOOTER
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer-footer.component.ts]: Example docs indentation needs to be 13 spaces because of how TypeScript handles indents in docs.

File: terminus-ui/drawer/src/drawer-header.component.ts [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+  ElementRef,
+  ViewEncapsulation,
+} from '@angular/core';
+
+/**
+ * The drawer header UI Component
+ *
+ * @example
+ * <ts-drawer-header>
+ *   THIS IS MY HEADER
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer-header.component.ts]: Example docs indentation needs to be 13 spaces because of how TypeScript handles indents in docs.

File: terminus-ui/drawer/src/drawer-header.component.ts [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+  changeDetection: ChangeDetectionStrategy.OnPush,
+  encapsulation: ViewEncapsulation.None,
+  exportAs: 'tsDrawerHeader',
+})
+export class TsDrawerHeaderComponent {
+
+  /**
+   * Return header native element
+   */
+  public get headerNativeElement() {
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer-header.component.ts]: Missing return type

File: terminus-ui/drawer/src/drawer-header.component.ts [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+    return this.elementRef.nativeElement;
+  }
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer-header.component.ts]: Missing line break before constructor

File: terminus-ui/drawer/src/drawer.component.ts [hunk 13]
```diff
@@ -131,6 +137,18 @@ export class TsDrawerComponent implements AfterContentChecked, OnDestroy {
    */
   public readonly modeChanged = new Subject();
 
+  /**
```
Comment (benjamincharity) [inline terminus-ui/drawer/src/drawer.component.ts]: I'll only tag it in one spot since we chatted via slack, but these content children and footer/header margin inputs are all not needed to meet our requirements list.

**Review by benjamincharity — CHANGES_REQUESTED** [review]

**Review by benjamincharity — APPROVED** [review]
🚀
