### PR TITLE
fix(daterange): on initial load, date range isn't getting value and status set properly

### LINKED ISSUE #1339: daterange isn't populating value and status properly on first load

### PR DESCRIPTION
**Pull request by atlwendy**
closes #1339

### CODE REVIEW

File: terminus-ui/date-range/src/date-range.component.ts [hunk 1]
```diff
@@ -274,6 +278,13 @@ export class TsDateRangeComponent implements OnInit, OnDestroy {
       return;
     }
 
+    this.changeDetectorRef.detectChanges();
+
+    // This is to fix on an initial load, date range value isn't populating correctly.
```
Comment (benjamincharity) [inline terminus-ui/date-range/src/date-range.component.ts]: Can we prefix this comment with `// HACK: etc..`? Using a standard prefix helps call these specific items out (ie `TODO` etc)

File: terminus-ui/date-range/src/date-range.component.ts [hunk 2]
```diff
@@ -7,6 +7,7 @@ import {
   OnInit,
   Output,
   ViewEncapsulation,
+  ChangeDetectorRef,
```
Comment (benjamincharity) [inline terminus-ui/date-range/src/date-range.component.ts]: We've started alphabetizing multi-imports. Looks like there is a vs code plugin that might be able to make it easy
