### PR TITLE
fix(Table): correctly set any possible column alignment

### LINKED ISSUE #2066: Table: Cell alignment only working for 'right'
As called out here: https://github.com/GetTerminus/terminus-ui/issues/767#issuecomment-595465677

The correct alignment classes are not getting set; only the right alignment works

### PR DESCRIPTION
**Pull request by benjamincharity**
ISSUES CLOSED: #2066

- fix table alignment not being set

### CODE REVIEW

File: projects/library/table/src/cell.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ export function setColumnAlignment(column: TsColumnDefDirective, renderer: Rende
         + `See "TsTableColumnAlignment" type for available options.`);
     }
 
-    renderer.addClass(elementRef.nativeElement, 'ts-cell--align-right');
+    renderer.addClass(elementRef.nativeElement, `ts-cell--align-${column.alignment}`);
```
Comment (atlwendy) [inline projects/library/table/src/cell.ts:63]: How did we not see this? lol

**Review by atlwendy — APPROVED** [review]
