### PR TITLE
fix(Select): Use formatUIFn function input for seeding autocomplete values

### LINKED ISSUE #1269: Select component cannot display selected object if it's not string

### PR DESCRIPTION
**Pull request by atlwendy**
closes #1269

### CODE REVIEW

File: terminus-ui/src/select/select.component.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ import {
   isString,
   TsDocumentService,
   untilComponentDestroyed,
+  isFunction,
```
Comment (benjamincharity) [inline terminus-ui/src/select/select.component.ts]: We've started keeping our imports somewhat alphabetical. Currently we are alphabetizing import collections like the above, but not every separate import statement.

This may make it easier: https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines

File: terminus-ui/src/select/select.component.ts [hunk 2]
```diff
@@ -685,6 +687,30 @@ export class TsSelectComponent implements
   }
   private _delimiter: string = DEFAULT_DELIMITER;
 
+  /**
+   * Define a function to retrieve the UI value for an option
+   */
+  @Input()
+  public set formatUIFn(value: TsSelectFormatFn) {
```
Comment (benjamincharity) [inline terminus-ui/src/select/select.component.ts]: Can we rename this to something more explicit? Maybe `chipFormatFn` or `chipFormatUIFn` etc just so it's clear this will only affect chips and not all selects.

File: terminus-ui/src/select/select.component.ts [hunk 3]
```diff
@@ -954,6 +980,15 @@ export class TsSelectComponent implements
         this.autocompleteFormControl.setValue(this.ngControl.value);
         this.autocompleteSelections = this.ngControl.value;
       }
+      if (this.ngControl.valueChanges) {
+        this.ngControl.valueChanges
+          .pipe(untilComponentDestroyed(this))
+          .subscribe((newValue) => {
+            if (this.autocomplete && newValue) {
```
Comment (benjamincharity) [inline terminus-ui/src/select/select.component.ts]: we can add `// istanbul ignore else` above this if so coverage will ignore the non-existent 'else' path
