### PR TITLE
fix(CsvEntry): make container scrollbar not showing up in firefox

### LINKED ISSUE #1689: CSV: Scrollbars issues in Firefox
It seems that in Firefox, the scrollbars are always present. The content may be slightly larger than the window.

When rows are added or removed the scrollbars flash in and out.

### PR DESCRIPTION
**Pull request by atlwendy**
closes #1689 #2025

### CODE REVIEW

File: terminus-ui/csv-entry/src/csv-entry.component.ts [hunk 1]
```diff
@@ -653,7 +653,6 @@ export class TsCSVEntryComponent implements OnInit, OnDestroy {
   public resetTable(): void {
     this.clearAllRows();
     this.clearHeaderCells();
-    this.columnCount = DEFAULT_COLUMN_COUNT;
```
Comment (benjamincharity) [inline terminus-ui/csv-entry/src/csv-entry.component.ts:656]: This breaks the use case where a user pastes more columns than the default, and then clicks to reset the table. 

A test should _definitely_ have caught this, so we need to add something in.

File: terminus-ui/csv-entry/src/csv-entry.component.scss [hunk 2]
```diff
@@ -40,6 +40,7 @@
   .c-csv-entry__scroll {
     // Odd height used to ensure that the table cuts off mid-cell so the user knows there is more content
     max-height: 28.5em;
+    overflow-x: -moz-hidden-unscrollable;
```
Comment (benjamincharity) [inline terminus-ui/csv-entry/src/csv-entry.component.scss:44]: We should probably add a note about why this is needed. Since we don't officially support anything other than chrome I could see this getting deleted down the line.

**Review by benjamincharity — CHANGES_REQUESTED** [review]
These two bug fixes should be different commits so that they both appear in our changelog.

File: terminus-ui/csv-entry/src/csv-entry.component.ts (hunk 1 above)
Comment (atlwendy) [reply terminus-ui/csv-entry/src/csv-entry.component.ts:656]: I tested it out in demo, it doesn’t break. The reason is that if there’s no columnCount provided, default value is used and if columnCount is provided, that value is used here for reset.
I see resetTable function is covered, so thought there’s no need to add additional tests.

File: terminus-ui/csv-entry/src/csv-entry.component.scss (hunk 2 above)
Comment (atlwendy) [reply terminus-ui/csv-entry/src/csv-entry.component.scss:44]: Ditto... a comment would definitely be nice. Was adding it but probably got removed when doing clean up (tried bunch of different things). Although I’d say this name is very Firefox specific :)

File: terminus-ui/csv-entry/src/csv-entry.component.ts (hunk 1 above)
Comment (atlwendy) [reply terminus-ui/csv-entry/src/csv-entry.component.ts:656]: Ah I see your use case, where you can actually expand the column number on fly (via copy/paste). And reset is supposed to reset it to original set up.

**Review by benjamincharity — APPROVED** [review]

**Comment by benjamincharity** [comment]
@atlwendy looks like we're not up to date with `release`
