### PR TITLE
fix(Chart): correctly dispose of the chart when needed

### LINKED ISSUE #1873: Chart: Dispose of chart before reinitializing in ngOnChanges
Currently we are re-initializing the chart if the visualization changes. We need to correctly dispose of the chart before calling `init` again.

- [ ] Fix issue
- [ ] Add tests

### PR DESCRIPTION
**Pull request by benjamincharity**
ISSUES CLOSED: #1873

- moved test components to `test` endpoint
- added test helpers
- refactor so chart is disposed of properly before initialization

### CODE REVIEW

File: terminus-ui/chart/src/chart.component.ts [hunk 1]
```diff
@@ -173,9 +183,12 @@ export class TsChartComponent implements OnInit, OnChanges, OnDestroy {
   /**
    * Initialize a chart
    */
-  private init(type: TsChartVisualizationOptions): void {
+  private createChart(type: TsChartVisualizationOptions): void {
     this.zone.runOutsideAngular(() => {
-      // Create the appropriate chart using a chained ternary
+      if (this.chart) {
+        this.chart.dispose();
```
Comment (atlwendy) [inline terminus-ui/chart/src/chart.component.ts:189]: Does this ensure that old chart gets destroyed before creating new one?

**Review by atlwendy — APPROVED** [review]

File: terminus-ui/chart/src/chart.component.ts (hunk 1 above)
Comment (benjamincharity) [reply terminus-ui/chart/src/chart.component.ts:189]: yeah, if the chart exists, we call the chart's dispose method.
